#!/bin/bash
#
#  Copyright (c) 2017, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

OTBR_TOP_BUILDDIR="${BUILD_DIR}/otbr"
readonly OTBR_TOP_BUILDDIR

OTBR_OPTIONS="${OTBR_OPTIONS:-}"
readonly OTBR_OPTIONS

REFERENCE_DEVICE="${REFERENCE_DEVICE:-0}"
readonly REFERENCE_DEVICE

otbr_uninstall()
{
  
    systemctl stop otbr-web || true
    systemctl stop otbr-agent || true
    systemctl disable otbr-web || true
    systemctl disable otbr-agent || true
    ! systemctl is-enabled otbr-web
    ! systemctl is-enabled otbr-agent
    killall otbr-web otbr-agent || true
    systemctl daemon-reload
    
}

otbr_install()
{
    local otbr_options=()

    if [[ ${OTBR_OPTIONS} ]]; then
        read -r -a otbr_options <<<"${OTBR_OPTIONS}"
    fi

    otbr_options=(
        "-DBUILD_TESTING=OFF"
        "-DCMAKE_INSTALL_PREFIX=/usr"
        "-DOTBR_DBUS=ON"
        "-DOTBR_DNSSD_DISCOVERY_PROXY=ON"
        "-DOTBR_SRP_ADVERTISING_PROXY=ON"
        "-DOTBR_INFRA_IF_NAME=${INFRA_IF_NAME}"
        "-DOTBR_MDNS=${OTBR_MDNS:=mDNSResponder}"
        # Force re-evaluation of version strings
        "-DOTBR_VERSION="
        "-DOT_PACKAGE_VERSION="
        "${otbr_options[@]}"
    )

    
    otbr_options+=("-DOTBR_WEB=ON")
    otbr_options+=("-DOTBR_BORDER_ROUTING=ON")
    otbr_options+=("-DOTBR_REST=ON")
    otbr_options+=("-DOTBR_BACKBONE_ROUTER=ON")
    otbr_options+=("-DOTBR_DUA_ROUTING=ON")
    otbr_options+=(
            "-DOTBR_NO_AUTO_ATTACH=1"
            "-DOT_REFERENCE_DEVICE=ON"
            "-DOT_DHCP6_CLIENT=ON"
            "-DOT_DHCP6_SERVER=ON"
            )
    otbr_options+=(
            "-DOTBR_NAT64=ON"
            "-DOT_POSIX_NAT64_CIDR=${NAT64_DYNAMIC_POOL:-192.168.255.0/24}"
            )

    
        systemctl reload dbus
        systemctl daemon-reload
        systemctl enable otbr-web 
        systemctl enable otbr-agent
        systemctl is-enabled otbr-agent 
        systemctl is-enabled otbr-web   
        systemctl enable testharness-discovery || true
        systemctl is-enabled testharness-discovery || echo 'Failed to enable otbr-agent!'
        

}

otbr_update()
{
    otbr_install
}
